// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OwnsManyIssue;

namespace OwnsManyIssue.Migrations
{
    [DbContext(typeof(OwnsManyIssueContext))]
    [Migration("20190303163035_CreateOwnsManyIssueDB")]
    partial class CreateOwnsManyIssueDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OwnsManyIssue.Aggregates.Aggregate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Aggregates");
                });

            modelBuilder.Entity("OwnsManyIssue.Aggregates.Aggregate", b =>
                {
                    b.OwnsOne("OwnsManyIssue.Aggregates.ValueObjects.FirstValueObject", "FirstValueObject", b1 =>
                        {
                            b1.Property<int>("AggregateId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.HasKey("AggregateId");

                            b1.ToTable("Aggregates");

                            b1.HasOne("OwnsManyIssue.Aggregates.Aggregate")
                                .WithOne("FirstValueObject")
                                .HasForeignKey("OwnsManyIssue.Aggregates.ValueObjects.FirstValueObject", "AggregateId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsMany("OwnsManyIssue.Aggregates.ValueObjects.SecondValueObject", "SecondValueObjects", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<int>("AggregateId");

                                    b2.HasKey("Id");

                                    b2.HasIndex("AggregateId");

                                    b2.ToTable("SecondValueObjects");

                                    b2.HasOne("OwnsManyIssue.Aggregates.ValueObjects.FirstValueObject")
                                        .WithMany("SecondValueObjects")
                                        .HasForeignKey("AggregateId")
                                        .OnDelete(DeleteBehavior.Cascade);

                                    b2.OwnsMany("OwnsManyIssue.Aggregates.ValueObjects.ThirdValueObject", "ThirdValueObjects", b3 =>
                                        {
                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                            b3.Property<int>("SecondValueObjectId");

                                            b3.HasKey("Id");

                                            b3.HasIndex("SecondValueObjectId");

                                            b3.ToTable("ThirdValueObjects");

                                            b3.HasOne("OwnsManyIssue.Aggregates.ValueObjects.SecondValueObject")
                                                .WithMany("ThirdValueObjects")
                                                .HasForeignKey("SecondValueObjectId")
                                                .OnDelete(DeleteBehavior.Cascade);

                                            b3.OwnsOne("OwnsManyIssue.Aggregates.ValueObjects.FourthValueObject", "FourthValueObject", b4 =>
                                                {
                                                    b4.Property<int>("ThirdValueObjectId")
                                                        .ValueGeneratedOnAdd()
                                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                                    b4.HasKey("ThirdValueObjectId");

                                                    b4.ToTable("ThirdValueObjects");

                                                    b4.HasOne("OwnsManyIssue.Aggregates.ValueObjects.ThirdValueObject")
                                                        .WithOne("FourthValueObject")
                                                        .HasForeignKey("OwnsManyIssue.Aggregates.ValueObjects.FourthValueObject", "ThirdValueObjectId")
                                                        .OnDelete(DeleteBehavior.Cascade);

                                                    b4.OwnsMany("OwnsManyIssue.Aggregates.ValueObjects.FifthValueObject", "FifthValueObjects", b5 =>
                                                        {
                                                            b5.Property<int>("Id")
                                                                .ValueGeneratedOnAdd()
                                                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                                            b5.Property<int>("AnyValue");

                                                            b5.Property<int>("ThirdValueObjectId");

                                                            b5.HasKey("Id");

                                                            b5.HasIndex("ThirdValueObjectId");

                                                            b5.ToTable("ThirdFifthValueObjects");

                                                            b5.HasOne("OwnsManyIssue.Aggregates.ValueObjects.FourthValueObject")
                                                                .WithMany("FifthValueObjects")
                                                                .HasForeignKey("ThirdValueObjectId")
                                                                .OnDelete(DeleteBehavior.Cascade);
                                                        });
                                                });
                                        });

                                    b2.OwnsOne("OwnsManyIssue.Aggregates.ValueObjects.FourthValueObject", "FourthValueObject", b3 =>
                                        {
                                            b3.Property<int>("SecondValueObjectId")
                                                .ValueGeneratedOnAdd()
                                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                            b3.HasKey("SecondValueObjectId");

                                            b3.ToTable("SecondValueObjects");

                                            b3.HasOne("OwnsManyIssue.Aggregates.ValueObjects.SecondValueObject")
                                                .WithOne("FourthValueObject")
                                                .HasForeignKey("OwnsManyIssue.Aggregates.ValueObjects.FourthValueObject", "SecondValueObjectId")
                                                .OnDelete(DeleteBehavior.Cascade);

                                            b3.OwnsMany("OwnsManyIssue.Aggregates.ValueObjects.FifthValueObject", "FifthValueObjects", b4 =>
                                                {
                                                    b4.Property<int>("Id")
                                                        .ValueGeneratedOnAdd()
                                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                                    b4.Property<int>("AnyValue");

                                                    b4.Property<int>("SecondValueObjectId");

                                                    b4.HasKey("Id");

                                                    b4.HasIndex("SecondValueObjectId");

                                                    b4.ToTable("FourthFifthValueObjects");

                                                    b4.HasOne("OwnsManyIssue.Aggregates.ValueObjects.FourthValueObject")
                                                        .WithMany("FifthValueObjects")
                                                        .HasForeignKey("SecondValueObjectId")
                                                        .OnDelete(DeleteBehavior.Cascade);
                                                });
                                        });
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
